# Generated by Django 3.1.6 on 2022-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('discription', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
