# Generated by Django 3.1.6 on 2022-08-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
